In [ ]:
# Imports
import pandas as pd
# Load data
df = pd.read_csv("../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [20]:
# Preview data
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

**What is one row?**
- One row = one customer

**So if one row is one customer:**
1. How many customers do we have?
2. Can a customer appear more than once?

In [92]:
print(f"Number of customers = {df.shape[0]}")
print(f"Number of features = {df.shape[1]}")
print(f"number of duplicated rows = {df.duplicated().sum()}")
print(f"number of duplicated customer IDs = {df['customerID'].duplicated().sum()}")
print(f"what are the customerID = {df['customerID'].unique()}")
print(f"Missing customerID: {df['customerID'].isna().sum()}")
print(f"what are the outputs = {df['Churn'].unique()}")
print(df["Churn"].value_counts(dropna=False))
print(df["Churn"].value_counts(dropna=False).sum())

Number of customers = 7043
Number of features = 21
number of duplicated rows = 0
number of duplicated customer IDs = 0
what are the customerID = <StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
Missing customerID: 0
what are the outputs = <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Churn
No     5174
Yes    1869
Name: count, dtype: int64
7043

**It's a supervised binary classification problem**

- We have output -> Supervised

- The output is either Yes or No -> binary

- Want to predict if a customer churn or not -> Classification

**customerID**

- No missing values.
- No duplicated customer IDs.
- Number of unique IDs equals the number of rows, so each row represents a unique customer.
- No cleaning is required.
- `customerID` is an identifier and should not be used as a predictive feature.

In [11]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [32]:
# This will show us if we have any missing values and the data types of each column
# If there is a missing value, we will have to decide how to handle it. We can either drop the rows with missing values or fill them with a default value.
# We should check if the data types are correct. For example, if a column is supposed to be numeric but is stored as a string, we will have to convert it to the correct data type.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [93]:
print("gender", df['gender'].unique(), "\n")
print(df["gender"].value_counts(dropna=False))
print(df["gender"].value_counts(dropna=False).sum())

print("SeniorCitizen", df['SeniorCitizen'].unique(), "\n")
print(df["SeniorCitizen"].value_counts(dropna=False))
print(df["SeniorCitizen"].value_counts(dropna=False).sum())

print("Partner", df['Partner'].unique(), "\n")
print(df["Partner"].value_counts(dropna=False))
print(df["Partner"].value_counts(dropna=False).sum())

print("Dependents", df['Dependents'].unique(), "\n")
print(df["Dependents"].value_counts(dropna=False))
print(df["Dependents"].value_counts(dropna=False).sum())

print("tenure", df['tenure'].unique(), "\n")
print(df["tenure"].value_counts(dropna=False))
print(df["tenure"].value_counts(dropna=False).sum())

print("PhoneService", df['PhoneService'].unique(), "\n")
print(df["PhoneService"].value_counts(dropna=False))
print(df["PhoneService"].value_counts(dropna=False).sum())

print("MultipleLines", df['MultipleLines'].unique(), "\n")
print(df["MultipleLines"].value_counts(dropna=False))
print(df["MultipleLines"].value_counts(dropna=False).sum())

print("InternetService", df['InternetService'].unique(), "\n")
print(df["InternetService"].value_counts(dropna=False))
print(df["InternetService"].value_counts(dropna=False).sum())

print("OnlineSecurity", df['OnlineSecurity'].unique(), "\n")
print(df["OnlineSecurity"].value_counts(dropna=False))
print(df["OnlineSecurity"].value_counts(dropna=False).sum())

print("OnlineBackup", df['OnlineBackup'].unique(), "\n")
print(df["OnlineBackup"].value_counts(dropna=False))
print(df["OnlineBackup"].value_counts(dropna=False).sum())

print("DeviceProtection", df['DeviceProtection'].unique(), "\n")
print(df["DeviceProtection"].value_counts(dropna=False))
print(df["DeviceProtection"].value_counts(dropna=False).sum())

print("TechSupport", df['TechSupport'].unique(), "\n")
print(df["TechSupport"].value_counts(dropna=False))
print(df["TechSupport"].value_counts(dropna=False).sum())

print("StreamingTV", df['StreamingTV'].unique(), "\n")
print(df["StreamingTV"].value_counts(dropna=False))
print(df["StreamingTV"].value_counts(dropna=False).sum())

print("StreamingMovies", df['StreamingMovies'].unique(), "\n")
print(df["StreamingMovies"].value_counts(dropna=False))
print(df["StreamingMovies"].value_counts(dropna=False).sum())

print("Contract", df['Contract'].unique(), "\n")
print(df["Contract"].value_counts(dropna=False))
print(df["Contract"].value_counts(dropna=False).sum())

print("PaperlessBilling", df['PaperlessBilling'].unique(), "\n")
print(df["PaperlessBilling"].value_counts(dropna=False))
print(df["PaperlessBilling"].value_counts(dropna=False).sum())

print("PaymentMethod", df['PaymentMethod'].unique(), "\n")
print(df["PaymentMethod"].value_counts(dropna=False))
print(df["PaymentMethod"].value_counts(dropna=False).sum())

print("MonthlyCharges", df['MonthlyCharges'].unique(), "\n")
print(df["MonthlyCharges"].value_counts(dropna=False))
print(df["MonthlyCharges"].value_counts(dropna=False).sum())

print("TotalCharges", df['TotalCharges'].unique(), "\n")
print(df["TotalCharges"].value_counts(dropna=False))
print(df["TotalCharges"].value_counts(dropna=False).sum())

gender <StringArray>
['Female', 'Male']
Length: 2, dtype: str

gender
Male      3555
Female    3488
Name: count, dtype: int64
7043
SeniorCitizen [0 1]

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64
7043
Partner <StringArray>
['Yes', 'No']
Length: 2, dtype: str

Partner
No     3641
Yes    3402
Name: count, dtype: int64
7043
Dependents <StringArray>
['No', 'Yes']
Length: 2, dtype: str

Dependents
No     4933
Yes    2110
Name: count, dtype: int64
7043
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]

tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64
7043
PhoneService <StringArray>
['No', 'Yes']
Length: 2, dtype: str

PhoneService
Yes    6361
No      682
Name: count, dtype: int64
7043
MultipleLines <StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64
7043
InternetService <StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64
7043
OnlineSecurity <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64
7043
OnlineBackup <StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64
7043
DeviceProtection <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64
7043
TechSupport <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64
7043
StreamingTV <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64
7043
StreamingMovies <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64
7043
Contract <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64
7043
PaperlessBilling <StringArray>
['Yes', 'No']
Length: 2, dtype: str

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64
7043
PaymentMethod <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64
7043
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]

MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
19.70     43
          ..
72.00      1
108.35     1
63.10      1
44.20      1
78.70      1
Name: count, Length: 1585, dtype: int64
7043
TotalCharges <StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str

TotalCharges
20.2      11
          11
19.75      9
19.9       8
20.05      8
          ..
1990.5     1
7362.9     1
346.45     1
306.6      1
6844.5     1
Name: count, Length: 6531, dtype: int64
7043

**As we can see, SeniorCitizen should be a boolean, and TotalCharges should be a float.** 

What values inside TotalCharges are preventing pandas from treating the entire column as numeric?

In [80]:
total_charges_numeric = pd.to_numeric(df["TotalCharges"], errors="coerce")
mask = total_charges_numeric.isna()
df.loc[mask]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [101]:
df.loc[df["tenure"] == 0]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [102]:
(df.loc[mask, "tenure"] == 0).all()

np.True_

So we can see when "tenure" == 0, then total charges is "" which makes sence.

In [64]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

Now I want to check if there is a same problem with other columns:

In [103]:
string_columns = df.select_dtypes(include=["object", "string"]).columns

for col in string_columns:
    blank_count = df[col].str.strip().eq("").sum()

    if blank_count > 0:
        print(f"{col}: {blank_count} blank values")

TotalCharges: 11 blank values

In [35]:
df["Churn"].value_counts(normalize=True)

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

So the data is inbalence and we should consider it when we want to evaluate the model.

In [108]:
print(df.loc[df["PhoneService"] == "No", "MultipleLines"].value_counts())
print(df.loc[df["MultipleLines"] == "No phone service", "PhoneService"].value_counts())
internet_features = [
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
]

for col in internet_features:
    print(col)
    print(df.loc[df["InternetService"] == "No", col].value_counts(), "\n")

MultipleLines
No phone service    682
Name: count, dtype: int64
PhoneService
No    682
Name: count, dtype: int64
OnlineSecurity
OnlineSecurity
No internet service    1526
Name: count, dtype: int64

OnlineBackup
OnlineBackup
No internet service    1526
Name: count, dtype: int64

DeviceProtection
DeviceProtection
No internet service    1526
Name: count, dtype: int64

TechSupport
TechSupport
No internet service    1526
Name: count, dtype: int64

StreamingTV
StreamingTV
No internet service    1526
Name: count, dtype: int64

StreamingMovies
StreamingMovies
No internet service    1526
Name: count, dtype: int64